head:
  serviceAccountName: ""
  resources:
    limits:
      cpu: "1"
      memory: "2G"
    requests:
      cpu: "1"
      memory: "2G"
  tolerations:
  - key: node
    operator: Equal
    value: ray_head
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node
            operator: In
            values:
            - "ray-head"

worker:
  groupName: worker
  replicas: 1
  minReplicas: 1
  maxReplicas: 3
  serviceAccountName: ""
  resources:
    limits:
      cpu: "1"
      memory: "1G"
    requests:
      cpu: "1"
      memory: "1G"
  tolerations:
  - key: node
    operator: Equal
    value: ray_worker
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node
            operator: In
            values:
            - "ray-worker"