head:
  serviceAccountName: ""
  resources:
    limits:
      cpu: "1"
      memory: "2G"
    requests:
      cpu: "1"
      memory: "2G"
  tolerations: []
  affinity: {}

worker:
  groupName: worker
  replicas: 1
  minReplicas: 1
  maxReplicas: 3
  serviceAccountName: ""
  resources:
    limits:
      cpu: "1"
      memory: "1G"
    requests:
      cpu: "1"
      memory: "1G"
  tolerations: []
  affinity: {}