apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo1
  namespace: workspace
  annotations:
    iam.gke.io/gcp-service-account: batch-demo@rtae-lab.iam.gserviceaccount.com
---
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: batch-inference
  namespace : workspace
spec:
  entrypoint: python crd-demo/sample/job.py
  shutdownAfterJobFinishes: true
  ttlSecondsAfterFinished: 60
  runtimeEnvYAML: |
    pip:
      - numpy
      - datasets
      - torch
      - torchvision
      - transformers
      - google-cloud-bigquery
    working_dir: "https://github.com/RTae/kuberay-demo/archive/master.zip"
  rayClusterSpec:
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
      template:
        metadata:
          annotations:
            gke-gcsfuse/volumes: "true"
            gke-gcsfuse/cpu-limit: "0"
            gke-gcsfuse/memory-limit: 5Gi
            gke-gcsfuse/ephemeral-storage-limit: 10Gi
        spec:
          serviceAccountName: demo1
          nodeSelector:
            iam.gke.io/gke-metadata-server-enabled: "true"
          containers:
          - name: ray-head
            image: rayproject/ray-ml:2.33.0.914af0-py311
            resources:
              limits:
                cpu: "2"
                memory: "4Gi"
              requests:
                cpu: "2"
                memory: "4Gi"
            ports:
            - containerPort: 6379
              name: gcs-server
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 8000
              name: serve
            env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: hf_api_token
            volumeMounts:
              - mountPath: /tmp/ray
                name: ray-logs
              - mountPath: /mnt/cluster_storage
                name: cluster-storage
          volumes:
            - name: ray-logs
              emptyDir: {}
            - name: cluster-storage
              csi:
                driver: gcsfuse.csi.storage.gke.io
                volumeAttributes:
                  bucketName: landing-data-zhsp
                  mountOptions: "implicit-dirs,uid=1000,gid=100"
          tolerations:
          - key: node
            operator: Equal
            value: ray_head
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node
                    operator: In
                    values:
                    - "ray-head"
    workerGroupSpecs:
    - replicas: 1
      minReplicas: 0
      maxReplicas: 2
      groupName: worker-group
      rayStartParams: {}
      template:
        metadata:
          annotations:
            gke-gcsfuse/volumes: "true"
            gke-gcsfuse/cpu-limit: "0"
            gke-gcsfuse/memory-limit: 5Gi
            gke-gcsfuse/ephemeral-storage-limit: 10Gi
        spec:
          serviceAccountName: demo1
          nodeSelector:
            iam.gke.io/gke-metadata-server-enabled: "true"
          containers:
          - name: task
            image: rayproject/ray-ml:2.33.0.914af0-py311-gpu
            resources:
              limits:
                cpu: "6"
                memory: "16Gi"
                nvidia.com/gpu: "1"
              requests:
                cpu: "6"
                memory: "16Gi"
                nvidia.com/gpu: "1"
            env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: hf_api_token
            volumeMounts:
              - mountPath: /tmp/ray
                name: ray-logs
              - mountPath: /mnt/cluster_storage
                name: cluster-storage
          volumes:
            - name: ray-logs
              emptyDir: {}
            - name: cluster-storage
              csi:
                driver: gcsfuse.csi.storage.gke.io
                volumeAttributes:
                  bucketName: landing-data-zhsp
                  mountOptions: "implicit-dirs,uid=1000,gid=100"
          tolerations:
          - key: node
            operator: Equal
            value: ray_worker
          - key: type
            operator: Equal
            value: small
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node
                    operator: In
                    values:
                    - "ray-worker"