[tool.poetry]
name = "load-test"
version = "0.1.0"
description = ""
authors = ["RTae"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.3"
typer = "^0.12.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
